<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    
    <!-- NuGet Metadata -->
    <PackageId>MAES.Fiskal2</PackageId>
    <Version>0.1.0</Version>
    <Authors>Roko Tomović</Authors>
    <Company>MAES</Company>
    <Description>C# biblioteka za rad s Hrvatskim fiskalnim posrednicima</Description>
    <PackageProjectUrl>https://github.com/MAES-Software/MAES.Fiskal2</PackageProjectUrl>
    <RepositoryUrl>https://github.com/MAES-Software/MAES.Fiskal2</RepositoryUrl>
    <PackageTags>Fiskalizacija2.0;Fiscalization2.0;Fiskal2;Fiskalizacija;Posrednici;</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <None Include="README.md" Pack="true" PackagePath="\"/>
    <None Include="LICENSE.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
