//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://fina.hr/eracun/b2b/ws/pki/v0.1", ConfigurationName="eRacunB2BPortType")]
public interface eRacunB2BPortType
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fina.hr/eracun/b2b/Echo", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<echoResponse> echoAsync(echoRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fina.hr/eracun/b2b/SendB2BOutgoingInvoice", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<sendB2BOutgoingInvoiceResponse> sendB2BOutgoingInvoiceAsync(sendB2BOutgoingInvoiceRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fina.hr/eracun/b2g/SendB2BOutgoingInvoiceReporting", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<sendB2BOutgoingInvoiceReportingResponse> sendB2BOutgoingInvoiceReportingAsync(sendB2BOutgoingInvoiceReportingRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://fina.hr/eracun/b2b/GetB2BOutgoingInvoiceStatus", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<getB2BOutgoingInvoiceStatusResponse> getB2BOutgoingInvoiceStatusAsync(getB2BOutgoingInvoiceStatusRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/Echo/v0.1")]
public partial class EchoMsg
{
    
    private HeaderSupplierType headerSupplierField;
    
    private EchoMsgData dataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1", Order=0)]
    public HeaderSupplierType HeaderSupplier
    {
        get
        {
            return this.headerSupplierField;
        }
        set
        {
            this.headerSupplierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public EchoMsgData Data
    {
        get
        {
            return this.dataField;
        }
        set
        {
            this.dataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1")]
public partial class HeaderSupplierType
{
    
    private string messageIDField;
    
    private string supplierIDField;
    
    private string additionalSupplierIDField;
    
    private string eRPIDField;
    
    private string messageTypeField;
    
    private string messageAttributesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string MessageID
    {
        get
        {
            return this.messageIDField;
        }
        set
        {
            this.messageIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string SupplierID
    {
        get
        {
            return this.supplierIDField;
        }
        set
        {
            this.supplierIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string AdditionalSupplierID
    {
        get
        {
            return this.additionalSupplierIDField;
        }
        set
        {
            this.additionalSupplierIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string ERPID
    {
        get
        {
            return this.eRPIDField;
        }
        set
        {
            this.eRPIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
    public string MessageType
    {
        get
        {
            return this.messageTypeField;
        }
        set
        {
            this.messageTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string MessageAttributes
    {
        get
        {
            return this.messageAttributesField;
        }
        set
        {
            this.messageAttributesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1")]
public partial class DocumentStatusType
{
    
    private DocumentStatusTypeStatusCode statusCodeField;
    
    private string statusTextField;
    
    private System.DateTime statusTimestampField;
    
    private bool statusTimestampFieldSpecified;
    
    private string noteField;
    
    private decimal partialAmountField;
    
    private bool partialAmountFieldSpecified;
    
    private string documentCurrencyCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public DocumentStatusTypeStatusCode StatusCode
    {
        get
        {
            return this.statusCodeField;
        }
        set
        {
            this.statusCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string StatusText
    {
        get
        {
            return this.statusTextField;
        }
        set
        {
            this.statusTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public System.DateTime StatusTimestamp
    {
        get
        {
            return this.statusTimestampField;
        }
        set
        {
            this.statusTimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusTimestampSpecified
    {
        get
        {
            return this.statusTimestampFieldSpecified;
        }
        set
        {
            this.statusTimestampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Note
    {
        get
        {
            return this.noteField;
        }
        set
        {
            this.noteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public decimal PartialAmount
    {
        get
        {
            return this.partialAmountField;
        }
        set
        {
            this.partialAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PartialAmountSpecified
    {
        get
        {
            return this.partialAmountFieldSpecified;
        }
        set
        {
            this.partialAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string DocumentCurrencyCode
    {
        get
        {
            return this.documentCurrencyCodeField;
        }
        set
        {
            this.documentCurrencyCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1")]
public enum DocumentStatusTypeStatusCode
{
    
    /// <remarks/>
    RECEIVED,
    
    /// <remarks/>
    PAYMENT_RECEIVED,
    
    /// <remarks/>
    RECEIVING_CONFIRMED,
    
    /// <remarks/>
    APPROVED,
    
    /// <remarks/>
    REJECTED,
    
    /// <remarks/>
    PAYMENT_FULFILLED,
    
    /// <remarks/>
    PAYMENT_PARTIALLY_FULFILLED,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1")]
public partial class MessageAckType
{
    
    private string messageIDField;
    
    private string messageAckIDField;
    
    private string messageTypeField;
    
    private AckStatusType ackStatusField;
    
    private int ackStatusCodeField;
    
    private string ackStatusTextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string MessageID
    {
        get
        {
            return this.messageIDField;
        }
        set
        {
            this.messageIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string MessageAckID
    {
        get
        {
            return this.messageAckIDField;
        }
        set
        {
            this.messageAckIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
    public string MessageType
    {
        get
        {
            return this.messageTypeField;
        }
        set
        {
            this.messageTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public AckStatusType AckStatus
    {
        get
        {
            return this.ackStatusField;
        }
        set
        {
            this.ackStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public int AckStatusCode
    {
        get
        {
            return this.ackStatusCodeField;
        }
        set
        {
            this.ackStatusCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string AckStatusText
    {
        get
        {
            return this.ackStatusTextField;
        }
        set
        {
            this.ackStatusTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1")]
public enum AckStatusType
{
    
    /// <remarks/>
    ACCEPTED,
    
    /// <remarks/>
    MSG_NOT_VALID,
    
    /// <remarks/>
    SYSTEM_ERROR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/Echo/v0.1")]
public partial class EchoMsgData
{
    
    private EchoMsgDataEchoData echoDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public EchoMsgDataEchoData EchoData
    {
        get
        {
            return this.echoDataField;
        }
        set
        {
            this.echoDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/Echo/v0.1")]
public partial class EchoMsgDataEchoData
{
    
    private string echoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Echo
    {
        get
        {
            return this.echoField;
        }
        set
        {
            this.echoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/Echo/v0.1")]
public partial class EchoAckMsg
{
    
    private MessageAckType messageAckField;
    
    private EchoAckMsgEchoData echoDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1", Order=0)]
    public MessageAckType MessageAck
    {
        get
        {
            return this.messageAckField;
        }
        set
        {
            this.messageAckField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public EchoAckMsgEchoData EchoData
    {
        get
        {
            return this.echoDataField;
        }
        set
        {
            this.echoDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/Echo/v0.1")]
public partial class EchoAckMsgEchoData
{
    
    private string echoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Echo
    {
        get
        {
            return this.echoField;
        }
        set
        {
            this.echoField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class echoRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fina.hr/eracun/b2b/pki/Echo/v0.1", Order=0)]
    public EchoMsg EchoMsg;
    
    public echoRequest()
    {
    }
    
    public echoRequest(EchoMsg EchoMsg)
    {
        this.EchoMsg = EchoMsg;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class echoResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fina.hr/eracun/b2b/pki/Echo/v0.1", Order=0)]
    public EchoAckMsg EchoAckMsg;
    
    public echoResponse()
    {
    }
    
    public echoResponse(EchoAckMsg EchoAckMsg)
    {
        this.EchoAckMsg = EchoAckMsg;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
public partial class SendB2BOutgoingInvoiceMsg
{
    
    private HeaderSupplierType headerSupplierField;
    
    private SendB2BOutgoingInvoiceMsgData dataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1", Order=0)]
    public HeaderSupplierType HeaderSupplier
    {
        get
        {
            return this.headerSupplierField;
        }
        set
        {
            this.headerSupplierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public SendB2BOutgoingInvoiceMsgData Data
    {
        get
        {
            return this.dataField;
        }
        set
        {
            this.dataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
public partial class SendB2BOutgoingInvoiceMsgData
{
    
    private SendB2BOutgoingInvoiceMsgDataB2BOutgoingInvoiceEnvelope b2BOutgoingInvoiceEnvelopeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SendB2BOutgoingInvoiceMsgDataB2BOutgoingInvoiceEnvelope B2BOutgoingInvoiceEnvelope
    {
        get
        {
            return this.b2BOutgoingInvoiceEnvelopeField;
        }
        set
        {
            this.b2BOutgoingInvoiceEnvelopeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
public partial class SendB2BOutgoingInvoiceMsgDataB2BOutgoingInvoiceEnvelope
{
    
    private SendB2BOutgoingInvoiceMsgDataB2BOutgoingInvoiceEnvelopeXMLStandard xMLStandardField;
    
    private SendB2BOutgoingInvoiceMsgDataB2BOutgoingInvoiceEnvelopeSpecificationIdentifier specificationIdentifierField;
    
    private string supplierInvoiceIDField;
    
    private string buyerIDField;
    
    private string additionalBuyerIDField;
    
    private byte[] itemField;
    
    private ItemChoiceType itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SendB2BOutgoingInvoiceMsgDataB2BOutgoingInvoiceEnvelopeXMLStandard XMLStandard
    {
        get
        {
            return this.xMLStandardField;
        }
        set
        {
            this.xMLStandardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public SendB2BOutgoingInvoiceMsgDataB2BOutgoingInvoiceEnvelopeSpecificationIdentifier SpecificationIdentifier
    {
        get
        {
            return this.specificationIdentifierField;
        }
        set
        {
            this.specificationIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string SupplierInvoiceID
    {
        get
        {
            return this.supplierInvoiceIDField;
        }
        set
        {
            this.supplierInvoiceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string BuyerID
    {
        get
        {
            return this.buyerIDField;
        }
        set
        {
            this.buyerIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string AdditionalBuyerID
    {
        get
        {
            return this.additionalBuyerIDField;
        }
        set
        {
            this.additionalBuyerIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CreditNoteEnvelope", typeof(byte[]), DataType="base64Binary", Order=5)]
    [System.Xml.Serialization.XmlElementAttribute("InvoiceEnvelope", typeof(byte[]), DataType="base64Binary", Order=5)]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public byte[] Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName
    {
        get
        {
            return this.itemElementNameField;
        }
        set
        {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
public enum SendB2BOutgoingInvoiceMsgDataB2BOutgoingInvoiceEnvelopeXMLStandard
{
    
    /// <remarks/>
    UBL,
    
    /// <remarks/>
    CII,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
public enum SendB2BOutgoingInvoiceMsgDataB2BOutgoingInvoiceEnvelopeSpecificationIdentifier
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("urn:cen.eu:en16931:2017")]
    urnceneuen169312017,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0")]
    urnceneuen169312017complianturnfdcpeppoleu2017poaccbilling30,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("urn:cen.eu:en16931:2017#compliant#urn:mfin.gov.hr:cius-2025:1.0#conformant#urn:mf" +
        "in.gov.hr:ext-2025:1.0")]
    urnceneuen169312017complianturnmfingovhrcius202510conformanturnmfingovhrext202510,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1", IncludeInSchema=false)]
public enum ItemChoiceType
{
    
    /// <remarks/>
    CreditNoteEnvelope,
    
    /// <remarks/>
    InvoiceEnvelope,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
public partial class SendB2BOutgoingInvoiceAckMsg
{
    
    private MessageAckType messageAckField;
    
    private SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelope b2BOutgoingInvoiceEnvelopeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1", Order=0)]
    public MessageAckType MessageAck
    {
        get
        {
            return this.messageAckField;
        }
        set
        {
            this.messageAckField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelope B2BOutgoingInvoiceEnvelope
    {
        get
        {
            return this.b2BOutgoingInvoiceEnvelopeField;
        }
        set
        {
            this.b2BOutgoingInvoiceEnvelopeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
public partial class SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelope
{
    
    private SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessing b2BOutgoingInvoiceProcessingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessing B2BOutgoingInvoiceProcessing
    {
        get
        {
            return this.b2BOutgoingInvoiceProcessingField;
        }
        set
        {
            this.b2BOutgoingInvoiceProcessingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
public partial class SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessing
{
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CorrectB2BOutgoingInvoice", typeof(SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessingCorrectB2BOutgoingInvoice), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("IncorrectB2BOutgoingInvoice", typeof(SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessingIncorrectB2BOutgoingInvoice), Order=0)]
    public object Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
public partial class SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessingCorrectB2BOutgoingInvoice
{
    
    private string supplierInvoiceIDField;
    
    private string invoiceIDField;
    
    private System.DateTime invoiceTimestampField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string SupplierInvoiceID
    {
        get
        {
            return this.supplierInvoiceIDField;
        }
        set
        {
            this.supplierInvoiceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
    public string InvoiceID
    {
        get
        {
            return this.invoiceIDField;
        }
        set
        {
            this.invoiceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public System.DateTime InvoiceTimestamp
    {
        get
        {
            return this.invoiceTimestampField;
        }
        set
        {
            this.invoiceTimestampField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
public partial class SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessingIncorrectB2BOutgoingInvoice
{
    
    private string supplierInvoiceIDField;
    
    private string errorCodeField;
    
    private string errorMessageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string SupplierInvoiceID
    {
        get
        {
            return this.supplierInvoiceIDField;
        }
        set
        {
            this.supplierInvoiceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string ErrorCode
    {
        get
        {
            return this.errorCodeField;
        }
        set
        {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string ErrorMessage
    {
        get
        {
            return this.errorMessageField;
        }
        set
        {
            this.errorMessageField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class sendB2BOutgoingInvoiceRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1", Order=0)]
    public SendB2BOutgoingInvoiceMsg SendB2BOutgoingInvoiceMsg;
    
    public sendB2BOutgoingInvoiceRequest()
    {
    }
    
    public sendB2BOutgoingInvoiceRequest(SendB2BOutgoingInvoiceMsg SendB2BOutgoingInvoiceMsg)
    {
        this.SendB2BOutgoingInvoiceMsg = SendB2BOutgoingInvoiceMsg;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class sendB2BOutgoingInvoiceResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1", Order=0)]
    public SendB2BOutgoingInvoiceAckMsg SendB2BOutgoingInvoiceAckMsg;
    
    public sendB2BOutgoingInvoiceResponse()
    {
    }
    
    public sendB2BOutgoingInvoiceResponse(SendB2BOutgoingInvoiceAckMsg SendB2BOutgoingInvoiceAckMsg)
    {
        this.SendB2BOutgoingInvoiceAckMsg = SendB2BOutgoingInvoiceAckMsg;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
public partial class SendB2BOutgoingInvoiceReportingMsg
{
    
    private HeaderSupplierType headerSupplierField;
    
    private SendB2BOutgoingInvoiceReportingMsgData dataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1", Order=0)]
    public HeaderSupplierType HeaderSupplier
    {
        get
        {
            return this.headerSupplierField;
        }
        set
        {
            this.headerSupplierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public SendB2BOutgoingInvoiceReportingMsgData Data
    {
        get
        {
            return this.dataField;
        }
        set
        {
            this.dataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
public partial class SendB2BOutgoingInvoiceReportingMsgData
{
    
    private SendB2BOutgoingInvoiceReportingMsgDataB2BOutgoingInvoiceEnvelope b2BOutgoingInvoiceEnvelopeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SendB2BOutgoingInvoiceReportingMsgDataB2BOutgoingInvoiceEnvelope B2BOutgoingInvoiceEnvelope
    {
        get
        {
            return this.b2BOutgoingInvoiceEnvelopeField;
        }
        set
        {
            this.b2BOutgoingInvoiceEnvelopeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
public partial class SendB2BOutgoingInvoiceReportingMsgDataB2BOutgoingInvoiceEnvelope
{
    
    private SendB2BOutgoingInvoiceReportingMsgDataB2BOutgoingInvoiceEnvelopeXMLStandard xMLStandardField;
    
    private SendB2BOutgoingInvoiceReportingMsgDataB2BOutgoingInvoiceEnvelopeSpecificationIdentifier specificationIdentifierField;
    
    private string supplierInvoiceIDField;
    
    private string buyerIDField;
    
    private string additionalBuyerIDField;
    
    private byte[] itemField;
    
    private ItemChoiceType1 itemElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SendB2BOutgoingInvoiceReportingMsgDataB2BOutgoingInvoiceEnvelopeXMLStandard XMLStandard
    {
        get
        {
            return this.xMLStandardField;
        }
        set
        {
            this.xMLStandardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public SendB2BOutgoingInvoiceReportingMsgDataB2BOutgoingInvoiceEnvelopeSpecificationIdentifier SpecificationIdentifier
    {
        get
        {
            return this.specificationIdentifierField;
        }
        set
        {
            this.specificationIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string SupplierInvoiceID
    {
        get
        {
            return this.supplierInvoiceIDField;
        }
        set
        {
            this.supplierInvoiceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string BuyerID
    {
        get
        {
            return this.buyerIDField;
        }
        set
        {
            this.buyerIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string AdditionalBuyerID
    {
        get
        {
            return this.additionalBuyerIDField;
        }
        set
        {
            this.additionalBuyerIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CreditNoteEnvelope", typeof(byte[]), DataType="base64Binary", Order=5)]
    [System.Xml.Serialization.XmlElementAttribute("InvoiceEnvelope", typeof(byte[]), DataType="base64Binary", Order=5)]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public byte[] Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName
    {
        get
        {
            return this.itemElementNameField;
        }
        set
        {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
public enum SendB2BOutgoingInvoiceReportingMsgDataB2BOutgoingInvoiceEnvelopeXMLStandard
{
    
    /// <remarks/>
    UBL,
    
    /// <remarks/>
    CII,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
public enum SendB2BOutgoingInvoiceReportingMsgDataB2BOutgoingInvoiceEnvelopeSpecificationIdentifier
{
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("urn:cen.eu:en16931:2017")]
    urnceneuen169312017,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0")]
    urnceneuen169312017complianturnfdcpeppoleu2017poaccbilling30,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("urn:cen.eu:en16931:2017#compliant#urn:mfin.gov.hr:cius-2025:1.0#conformant#urn:mf" +
        "in.gov.hr:ext-2025:1.0")]
    urnceneuen169312017complianturnmfingovhrcius202510conformanturnmfingovhrext202510,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1", IncludeInSchema=false)]
public enum ItemChoiceType1
{
    
    /// <remarks/>
    CreditNoteEnvelope,
    
    /// <remarks/>
    InvoiceEnvelope,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
public partial class SendB2BOutgoingInvoiceReportingAckMsg
{
    
    private MessageAckType messageAckField;
    
    private SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelope b2BOutgoingInvoiceEnvelopeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1", Order=0)]
    public MessageAckType MessageAck
    {
        get
        {
            return this.messageAckField;
        }
        set
        {
            this.messageAckField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelope B2BOutgoingInvoiceEnvelope
    {
        get
        {
            return this.b2BOutgoingInvoiceEnvelopeField;
        }
        set
        {
            this.b2BOutgoingInvoiceEnvelopeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
public partial class SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelope
{
    
    private SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessing b2BOutgoingInvoiceProcessingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessing B2BOutgoingInvoiceProcessing
    {
        get
        {
            return this.b2BOutgoingInvoiceProcessingField;
        }
        set
        {
            this.b2BOutgoingInvoiceProcessingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
public partial class SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessing
{
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CorrectB2BOutgoingInvoice", typeof(SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessingCorrectB2BOutgoingInvoice), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("IncorrectB2BOutgoingInvoice", typeof(SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessingIncorrectB2BOutgoingInvoice), Order=0)]
    public object Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
public partial class SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessingCorrectB2BOutgoingInvoice
{
    
    private string supplierInvoiceIDField;
    
    private string invoiceIDField;
    
    private System.DateTime invoiceTimestampField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string SupplierInvoiceID
    {
        get
        {
            return this.supplierInvoiceIDField;
        }
        set
        {
            this.supplierInvoiceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
    public string InvoiceID
    {
        get
        {
            return this.invoiceIDField;
        }
        set
        {
            this.invoiceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public System.DateTime InvoiceTimestamp
    {
        get
        {
            return this.invoiceTimestampField;
        }
        set
        {
            this.invoiceTimestampField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
public partial class SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessingIncorrectB2BOutgoingInvoice
{
    
    private string supplierInvoiceIDField;
    
    private string errorCodeField;
    
    private string errorMessageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string SupplierInvoiceID
    {
        get
        {
            return this.supplierInvoiceIDField;
        }
        set
        {
            this.supplierInvoiceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string ErrorCode
    {
        get
        {
            return this.errorCodeField;
        }
        set
        {
            this.errorCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string ErrorMessage
    {
        get
        {
            return this.errorMessageField;
        }
        set
        {
            this.errorMessageField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class sendB2BOutgoingInvoiceReportingRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1", Order=0)]
    public SendB2BOutgoingInvoiceReportingMsg SendB2BOutgoingInvoiceReportingMsg;
    
    public sendB2BOutgoingInvoiceReportingRequest()
    {
    }
    
    public sendB2BOutgoingInvoiceReportingRequest(SendB2BOutgoingInvoiceReportingMsg SendB2BOutgoingInvoiceReportingMsg)
    {
        this.SendB2BOutgoingInvoiceReportingMsg = SendB2BOutgoingInvoiceReportingMsg;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class sendB2BOutgoingInvoiceReportingResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1", Order=0)]
    public SendB2BOutgoingInvoiceReportingAckMsg SendB2BOutgoingInvoiceReportingAckMsg;
    
    public sendB2BOutgoingInvoiceReportingResponse()
    {
    }
    
    public sendB2BOutgoingInvoiceReportingResponse(SendB2BOutgoingInvoiceReportingAckMsg SendB2BOutgoingInvoiceReportingAckMsg)
    {
        this.SendB2BOutgoingInvoiceReportingAckMsg = SendB2BOutgoingInvoiceReportingAckMsg;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/GetB2BOutgoingInvoiceStatus/v0.1")]
public partial class GetB2BOutgoingInvoiceStatusMsg
{
    
    private HeaderSupplierType headerSupplierField;
    
    private GetB2BOutgoingInvoiceStatusMsgData dataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1", Order=0)]
    public HeaderSupplierType HeaderSupplier
    {
        get
        {
            return this.headerSupplierField;
        }
        set
        {
            this.headerSupplierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public GetB2BOutgoingInvoiceStatusMsgData Data
    {
        get
        {
            return this.dataField;
        }
        set
        {
            this.dataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/GetB2BOutgoingInvoiceStatus/v0.1")]
public partial class GetB2BOutgoingInvoiceStatusMsgData
{
    
    private GetB2BOutgoingInvoiceStatusMsgDataB2BOutgoingInvoiceStatus b2BOutgoingInvoiceStatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public GetB2BOutgoingInvoiceStatusMsgDataB2BOutgoingInvoiceStatus B2BOutgoingInvoiceStatus
    {
        get
        {
            return this.b2BOutgoingInvoiceStatusField;
        }
        set
        {
            this.b2BOutgoingInvoiceStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/GetB2BOutgoingInvoiceStatus/v0.1")]
public partial class GetB2BOutgoingInvoiceStatusMsgDataB2BOutgoingInvoiceStatus
{
    
    private string supplierInvoiceIDField;
    
    private string invoiceYearField;
    
    private bool documentCurrencyCodeField;
    
    private bool documentCurrencyCodeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string SupplierInvoiceID
    {
        get
        {
            return this.supplierInvoiceIDField;
        }
        set
        {
            this.supplierInvoiceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
    public string InvoiceYear
    {
        get
        {
            return this.invoiceYearField;
        }
        set
        {
            this.invoiceYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public bool DocumentCurrencyCode
    {
        get
        {
            return this.documentCurrencyCodeField;
        }
        set
        {
            this.documentCurrencyCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DocumentCurrencyCodeSpecified
    {
        get
        {
            return this.documentCurrencyCodeFieldSpecified;
        }
        set
        {
            this.documentCurrencyCodeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/GetB2BOutgoingInvoiceStatus/v0.1")]
public partial class GetB2BOutgoingInvoiceStatusAckMsg
{
    
    private MessageAckType messageAckField;
    
    private GetB2BOutgoingInvoiceStatusAckMsgB2BOutgoingInvoiceStatus b2BOutgoingInvoiceStatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1", Order=0)]
    public MessageAckType MessageAck
    {
        get
        {
            return this.messageAckField;
        }
        set
        {
            this.messageAckField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public GetB2BOutgoingInvoiceStatusAckMsgB2BOutgoingInvoiceStatus B2BOutgoingInvoiceStatus
    {
        get
        {
            return this.b2BOutgoingInvoiceStatusField;
        }
        set
        {
            this.b2BOutgoingInvoiceStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/GetB2BOutgoingInvoiceStatus/v0.1")]
public partial class GetB2BOutgoingInvoiceStatusAckMsgB2BOutgoingInvoiceStatus
{
    
    private string supplierIDField;
    
    private string additionalSupplierIDField;
    
    private string invoiceIDField;
    
    private string supplierInvoiceIDField;
    
    private System.DateTime invoiceTimestampField;
    
    private DocumentStatusType[] documentStatusField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string SupplierID
    {
        get
        {
            return this.supplierIDField;
        }
        set
        {
            this.supplierIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string AdditionalSupplierID
    {
        get
        {
            return this.additionalSupplierIDField;
        }
        set
        {
            this.additionalSupplierIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
    public string InvoiceID
    {
        get
        {
            return this.invoiceIDField;
        }
        set
        {
            this.invoiceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string SupplierInvoiceID
    {
        get
        {
            return this.supplierInvoiceIDField;
        }
        set
        {
            this.supplierInvoiceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public System.DateTime InvoiceTimestamp
    {
        get
        {
            return this.invoiceTimestampField;
        }
        set
        {
            this.invoiceTimestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DocumentStatus", Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1", Order=5)]
    public DocumentStatusType[] DocumentStatus
    {
        get
        {
            return this.documentStatusField;
        }
        set
        {
            this.documentStatusField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getB2BOutgoingInvoiceStatusRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fina.hr/eracun/b2b/pki/GetB2BOutgoingInvoiceStatus/v0.1", Order=0)]
    public GetB2BOutgoingInvoiceStatusMsg GetB2BOutgoingInvoiceStatusMsg;
    
    public getB2BOutgoingInvoiceStatusRequest()
    {
    }
    
    public getB2BOutgoingInvoiceStatusRequest(GetB2BOutgoingInvoiceStatusMsg GetB2BOutgoingInvoiceStatusMsg)
    {
        this.GetB2BOutgoingInvoiceStatusMsg = GetB2BOutgoingInvoiceStatusMsg;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class getB2BOutgoingInvoiceStatusResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fina.hr/eracun/b2b/pki/GetB2BOutgoingInvoiceStatus/v0.1", Order=0)]
    public GetB2BOutgoingInvoiceStatusAckMsg GetB2BOutgoingInvoiceStatusAckMsg;
    
    public getB2BOutgoingInvoiceStatusResponse()
    {
    }
    
    public getB2BOutgoingInvoiceStatusResponse(GetB2BOutgoingInvoiceStatusAckMsg GetB2BOutgoingInvoiceStatusAckMsg)
    {
        this.GetB2BOutgoingInvoiceStatusAckMsg = GetB2BOutgoingInvoiceStatusAckMsg;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public interface eRacunB2BPortTypeChannel : eRacunB2BPortType, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public partial class eRacunB2BPortTypeClient : System.ServiceModel.ClientBase<eRacunB2BPortType>, eRacunB2BPortType
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public eRacunB2BPortTypeClient() : 
            base(eRacunB2BPortTypeClient.GetDefaultBinding(), eRacunB2BPortTypeClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.eRacunB2BPortType.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public eRacunB2BPortTypeClient(EndpointConfiguration endpointConfiguration) : 
            base(eRacunB2BPortTypeClient.GetBindingForEndpoint(endpointConfiguration), eRacunB2BPortTypeClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public eRacunB2BPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(eRacunB2BPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public eRacunB2BPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(eRacunB2BPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public eRacunB2BPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<echoResponse> eRacunB2BPortType.echoAsync(echoRequest request)
    {
        return base.Channel.echoAsync(request);
    }
    
    public System.Threading.Tasks.Task<echoResponse> echoAsync(EchoMsg EchoMsg)
    {
        echoRequest inValue = new echoRequest();
        inValue.EchoMsg = EchoMsg;
        return ((eRacunB2BPortType)(this)).echoAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<sendB2BOutgoingInvoiceResponse> eRacunB2BPortType.sendB2BOutgoingInvoiceAsync(sendB2BOutgoingInvoiceRequest request)
    {
        return base.Channel.sendB2BOutgoingInvoiceAsync(request);
    }
    
    public System.Threading.Tasks.Task<sendB2BOutgoingInvoiceResponse> sendB2BOutgoingInvoiceAsync(SendB2BOutgoingInvoiceMsg SendB2BOutgoingInvoiceMsg)
    {
        sendB2BOutgoingInvoiceRequest inValue = new sendB2BOutgoingInvoiceRequest();
        inValue.SendB2BOutgoingInvoiceMsg = SendB2BOutgoingInvoiceMsg;
        return ((eRacunB2BPortType)(this)).sendB2BOutgoingInvoiceAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<sendB2BOutgoingInvoiceReportingResponse> eRacunB2BPortType.sendB2BOutgoingInvoiceReportingAsync(sendB2BOutgoingInvoiceReportingRequest request)
    {
        return base.Channel.sendB2BOutgoingInvoiceReportingAsync(request);
    }
    
    public System.Threading.Tasks.Task<sendB2BOutgoingInvoiceReportingResponse> sendB2BOutgoingInvoiceReportingAsync(SendB2BOutgoingInvoiceReportingMsg SendB2BOutgoingInvoiceReportingMsg)
    {
        sendB2BOutgoingInvoiceReportingRequest inValue = new sendB2BOutgoingInvoiceReportingRequest();
        inValue.SendB2BOutgoingInvoiceReportingMsg = SendB2BOutgoingInvoiceReportingMsg;
        return ((eRacunB2BPortType)(this)).sendB2BOutgoingInvoiceReportingAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getB2BOutgoingInvoiceStatusResponse> eRacunB2BPortType.getB2BOutgoingInvoiceStatusAsync(getB2BOutgoingInvoiceStatusRequest request)
    {
        return base.Channel.getB2BOutgoingInvoiceStatusAsync(request);
    }
    
    public System.Threading.Tasks.Task<getB2BOutgoingInvoiceStatusResponse> getB2BOutgoingInvoiceStatusAsync(GetB2BOutgoingInvoiceStatusMsg GetB2BOutgoingInvoiceStatusMsg)
    {
        getB2BOutgoingInvoiceStatusRequest inValue = new getB2BOutgoingInvoiceStatusRequest();
        inValue.GetB2BOutgoingInvoiceStatusMsg = GetB2BOutgoingInvoiceStatusMsg;
        return ((eRacunB2BPortType)(this)).getB2BOutgoingInvoiceStatusAsync(inValue);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    #if !NET6_0_OR_GREATER
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    #endif
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.eRacunB2BPortType))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.eRacunB2BPortType))
        {
            return new System.ServiceModel.EndpointAddress("http://address/SendB2BOutgoingInvoicePKIWebService");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return eRacunB2BPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.eRacunB2BPortType);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return eRacunB2BPortTypeClient.GetEndpointAddress(EndpointConfiguration.eRacunB2BPortType);
    }
    
    public enum EndpointConfiguration
    {
        
        eRacunB2BPortType,
    }
}
